name: update codex version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  codex-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: update codex version
        run: |
          ./.github/scripts/check-codex-update.sh

      - name: create pr
        uses: peter-evans/create-pull-request@v8
        with:
          sign-commits: true
          commit-message: "chore: bump codex version"
          title: "chore: bump codex version"
          body: |
            automated update of codex version.
          branch: chore/codex-version-bump
